# remote_theme: pmarsceill/just-the-docs
# color_scheme: "nil"
# title: "CS-770 HCI"
# subtitle: "CS/Psych/EdPsych-770 Human-Computer Interaction"
# author: Professor Mutlu
# description: "CS/Psych/EdPsych-770 Human-Computer Interaction, Spring 2020, Professor Mutlu, University of Wisconsin--Madison"
# search_enabled: true
# footer_content: "Copyright &copy; 2020 Professor <a href="mailto:bilge@cs.wisc.edu">Bilge Mutlu</a>."
# header_pages:
#   - index.md
#   - schedule.md
#   - syllabus.md
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
title: CS-639 HCI
description: Content
search_enabled: true
