remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
title: CS-770 HCI
description: CS/Psych/EdPsych-770 Human-Computer Interaction, Spring 2020, Professor Bilge Mutlu, University of Wisconsin--Madison
search_enabled: true
header_pages:
  - index.md
  - syllabus.md
